name: ILOT Builder

on:
  push:
    branches:
      - main

jobs:  
  init:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Test runner setup
        run: |
          ls -la .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
